services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app       # Source code sync for hot reload
      - /app/tmp             # Air temp directory (anonymous volume)
    ports:
      - "1323:1323"
    command: ["air", "-c", ".air.toml"]

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/yarn.lock:/app/yarn.lock:ro
      - ./frontend/.yarn:/app/.yarn:ro
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://localhost:1323/api

